version: '3.8'

services:
  pgsqldb:
    image: postgres:14.3
    environment:
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASS}'
      POSTGRES_DB: '${PG_NAME}'
    ports:
      - 5432:5432
    volumes:
      - pgsqldata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - pgsqldb

volumes:
  node_modules:
  pgsqldata:
